sudo: required
dist: trusty
language: node_js
deploy:
  exclude: "/client/components/elements/LoginTabs.jsx"

node_js:
  - 6

script:
  - npm test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
